services:
  - type: worker
    name: instagram-repost-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your-telegram-token
      - key: INSTAGRAM_USERNAME
        value: your-ig-username
      - key: INSTAGRAM_PASSWORD
        value: your-ig-password
